//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brusnika.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BrusnikaDbEntities : DbContext
    {
        public BrusnikaDbEntities()
            : base("name=BrusnikaDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Category> Category { get; set; }
        public DbSet<Delivery> Delivery { get; set; }
        public DbSet<DIsh> DIsh { get; set; }
        public DbSet<DishDelivery> DishDelivery { get; set; }
        public DbSet<User> User { get; set; }
    }
}
