//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brusnika.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public Delivery()
        {
            this.DishDelivery = new HashSet<DishDelivery>();
        }
    
        public int Id { get; set; }
        public System.DateTime DateTIme { get; set; }
        public string Adress { get; set; }
        public string PhoneNumber { get; set; }
        public string Comment { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<DishDelivery> DishDelivery { get; set; }
    }
}
