//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brusnika.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIsh
    {
        public DIsh()
        {
            this.DishDelivery = new HashSet<DishDelivery>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CategoryId { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<DishDelivery> DishDelivery { get; set; }
    }
}
